In [1]:
#1
import numpy as np

empty_array = np.empty((1, 2)) 
full_array = np.full((4, 5), 9)  

print("Empty Array:\n",empty_array)
print("\nFull Array:\n",full_array)

Empty Array:
 [[7.00092127e+286 9.84643903e+095]]

Full Array:
 [[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]


In [2]:
#12
in_arr1 = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
in_arr2 = np.array([[2,3,4],
                    [5,6,7],
                    [8,9,10]])
print("1st input array:\n",in_arr1)
print("2nt input array:\n",in_arr2)
out_arr = np.multiply(in_arr2,in_arr2)
print("Resultant output array:\n",out_arr)

1st input array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
2nt input array:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
Resultant output array:
 [[  4   9  16]
 [ 25  36  49]
 [ 64  81 100]]


In [3]:
#10
array1 = np.array([[1, 2],[3, 4]])
array2 = np.array([[5, 6],[7, 8]])
stacked_array = np.hstack((array1, array2))
print("Array 1:\n",array1)
print("\nArray 2:\n",array2)
print("\nHorizontally Stacked Array:\n",stacked_array)

Array 1:
 [[1 2]
 [3 4]]

Array 2:
 [[5 6]
 [7 8]]

Horizontally Stacked Array:
 [[1 2 5 6]
 [3 4 7 8]]


In [4]:
#9
a = np.array([[1, 0, 0],
              [1, 1, 1],
              [0, 0, 0]])

boolean_array = (a == 1)

print("Original Binary Array:\n",a)
print("\nBoolean Array:\n",boolean_array)

Original Binary Array:
 [[1 0 0]
 [1 1 1]
 [0 0 0]]

Boolean Array:
 [[ True False False]
 [ True  True  True]
 [False False False]]


In [5]:
#8
a = np.array([[2.5, 3.8, 1.5],
              [4.7, 2.9, 1.56]])
reshaped_array = a.reshape(1,6)
print("Original Array:\n",a)
print("\nReshaped Array:\n",reshaped_array)

Original Array:
 [[2.5  3.8  1.5 ]
 [4.7  2.9  1.56]]

Reshaped Array:
 [[2.5  3.8  1.5  4.7  2.9  1.56]]


In [6]:
#7
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

scalar = 2
result = matrix * scalar
print("Original Matrix:\n",matrix)
print("\nScalar:\n",scalar)
print("\nResult after Multiplication:\n",result)

Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Scalar:
 2

Result after Multiplication:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [7]:
#5
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result = np.add(array1, array2)
print("Array 1:\n",array1)
print("\nArray 2:\n",array2)
print("\nResult of Element-wise Addition:\n",result)

Array 1:
 [1 2 3]

Array 2:
 [4 5 6]

Result of Element-wise Addition:
 [5 7 9]


In [8]:
#4
arr = np.array([1,2,3,4,5,1,2,1,1,1])
print("Original array:\n",arr)
print("Most frequent value in the above array:")
print(np.bincount(arr).argmax())

Original array:
 [1 2 3 4 5 1 2 1 1 1]
Most frequent value in the above array:
1


In [9]:
#2
arr = np.array([[10.5,22.5,3.8],[41,np.nan,np.nan]])
print("Given array:\n",arr)
print("\nRemove all rows containing non-numeric elements:\n",arr[~np.isnan(arr).any(axis=1)])

Given array:
 [[10.5 22.5  3.8]
 [41.   nan  nan]]

Remove all rows containing non-numeric elements:
 [[10.5 22.5  3.8]]


In [10]:
#3
arr = np.array([[2, 8, 9, 4], 
                [9, 4, 9, 4],
                [4, 5, 9, 7],
                [2, 9, 4, 3]])

output = repr(arr).count("9, 4")
print(output)

4


In [11]:
#6
arr = np.array([1, 2, 3, 4, 5, 6]) 
condition = arr > 3 
indices = np.where(condition) 
print(indices)

(array([3, 4, 5], dtype=int64),)
